-- MySQL Script generated by MySQL Workbench
-- Mon Jun 13 21:42:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema criminal_evidence_management_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema criminal_evidence_management_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `criminal_evidence_management_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `criminal_evidence_management_system` ;

-- -----------------------------------------------------
-- Table `criminal_evidence_management_system`.`casestatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criminal_evidence_management_system`.`casestatus` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `criminal_evidence_management_system`.`casetype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criminal_evidence_management_system`.`casetype` (
  `id` INT NOT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `criminal_evidence_management_system`.`criminalcase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criminal_evidence_management_system`.`criminalcase` (
  `id` INT NOT NULL,
  `version` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `modifield` DATETIME NULL DEFAULT NULL,
  `number` VARCHAR(255) NULL DEFAULT NULL,
  `idCaseType` INT NULL DEFAULT NULL,
  `shortDescription` VARCHAR(255) NULL DEFAULT NULL,
  `detailDescription` VARCHAR(255) NULL DEFAULT NULL,
  `idCaseStatus` INT NULL DEFAULT NULL,
  `idLeadInvestigator` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `criminal_evidence_management_system`.`criminalcase_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criminal_evidence_management_system`.`criminalcase_detail` (
  `id` INT NOT NULL,
  `idCriminalCae` INT NULL DEFAULT NULL,
  `idDetective` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `criminal_evidence_management_system`.`detective`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criminal_evidence_management_system`.`detective` (
  `idPerson` INT NOT NULL,
  `badgeNumber` VARCHAR(255) NULL DEFAULT NULL,
  `idRank` INT NULL DEFAULT NULL,
  `armed` TINYINT NULL DEFAULT NULL,
  `idEmploymenStatus` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `criminal_evidence_management_system`.`employmentstatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criminal_evidence_management_system`.`employmentstatus` (
  `id` INT NOT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `criminal_evidence_management_system`.`evidence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criminal_evidence_management_system`.`evidence` (
  `id` INT NOT NULL,
  `version` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `modifield` DATETIME NULL DEFAULT NULL,
  `idCriminalCase` INT NULL DEFAULT NULL,
  `idStorage` INT NULL DEFAULT NULL,
  `number` VARCHAR(255) NULL DEFAULT NULL,
  `itemName` VARCHAR(255) NULL DEFAULT NULL,
  `notes` VARCHAR(255) NULL DEFAULT NULL,
  `archived` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `criminal_evidence_management_system`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criminal_evidence_management_system`.`person` (
  `id` INT NOT NULL,
  `version` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `modifield` DATETIME NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `firstName` VARCHAR(255) NULL DEFAULT NULL,
  `lastName` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `hiringDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `criminal_evidence_management_system`.`rank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criminal_evidence_management_system`.`rank` (
  `id` INT NOT NULL,
  `rank` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `criminal_evidence_management_system`.`storage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criminal_evidence_management_system`.`storage` (
  `id` INT NOT NULL,
  `version` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `modifield` DATETIME NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `criminal_evidence_management_system`.`trackaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criminal_evidence_management_system`.`trackaction` (
  `id` INT NOT NULL,
  `action` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `criminal_evidence_management_system`.`trackentry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criminal_evidence_management_system`.`trackentry` (
  `id` INT NOT NULL,
  `version` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `modifield` DATETIME NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `idEvidence` INT NULL DEFAULT NULL,
  `idDetective` INT NULL DEFAULT NULL,
  `idAction` INT NULL DEFAULT NULL,
  `reason` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
